version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432 
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - cs-produtos-infra-bd_default
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 
    networks:
      - cs-produtos-infra-bd_default

networks:
  cs-produtos-infra-bd_default:
    external: true
