INSERT INTO produtos (nome, preco) VALUES
    ('Arroz', 10.99),
    ('Feijão', 8.50),
    ('Açúcar', 5.99),
    ('Café', 12.75),
    ('Óleo de Soja', 6.49),
    ('Leite', 3.99),
    ('Pão de Forma', 4.25),
    ('Macarrão', 2.99),
    ('Sal', 1.49),
    ('Farinha de Trigo', 3.25),
    ('Manteiga', 7.99),
    ('Queijo Prato', 15.50),
    ('Presunto', 9.75),
    ('Peito de Frango', 12.99),
    ('Alcatra', 22.50),
    ('Salsicha', 6.25),
    ('Iogurte', 2.75),
    ('Ovos', 5.49),
    ('Batata', 4.99),
    ('Cenoura', 2.25),
    ('Tomate', 3.99),
    ('Alface', 1.75),
    ('Cebola', 1.99),
    ('Abacaxi', 4.50),
    ('Maçã', 3.25),
    ('Banana', 2.99),
    ('Laranja', 3.49),
    ('Melancia', 8.99),
    ('Uva', 6.75),
    ('Morango', 5.25),
    ('Pêssego', 4.99),
    ('Mamão', 3.75),
    ('Melão', 6.50),
    ('Ameixa', 7.25),
    ('Pera', 3.99),
    ('Pimentão', 2.99),
    ('Brócolis', 2.25),
    ('Cenoura', 1.75),
    ('Ervilha', 2.49),
    ('Milho Verde', 1.99),
    ('Cogumelos', 5.50),
    ('Refrigerante Cola', 4.25),
    ('Refrigerante Guaraná', 4.25),
    ('Refrigerante Limão', 4.25),
    ('Suco de Laranja', 6.99),
    ('Suco de Uva', 7.50),
    ('Suco de Maracujá', 5.99),
    ('Suco de Abacaxi', 5.99),
    ('Suco de Morango', 6.50),
    ('Cerveja', 2.99),
    ('Vinho Tinto', 15.99),
    ('Vinho Branco', 14.50),
    ('Vodka', 25.75),
    ('Whisky', 40.99),
    ('Rum', 18.25),
    ('Tequila', 30.49),
    ('Limpador Multiuso', 3.99),
    ('Detergente', 2.49),
    ('Sabão em Pó', 6.99),
    ('Desinfetante', 4.25),
    ('Esponja de Limpeza', 1.99),
    ('Papel Higiênico', 7.50),
    ('Sabonete', 2.99),
    ('Shampoo', 8.25),
    ('Condicionador', 9.75),
    ('Creme Dental', 3.25),
    ('Escova de Dentes', 2.50),
    ('Fio Dental', 1.99),
    ('Desodorante', 10.99),
    ('Perfume', 35.50),
    ('Protetor Solar', 15.75),
    ('Repelente', 9.99),
    ('Shampoo Anticaspa', 7.25),
    ('Condicionador Hidratante', 8.99),
    ('Gel para Cabelo', 6.50),
    ('Máscara Facial', 4.25),
    ('Creme Hidratante', 12.99),
    ('Loção Corporal', 10.75),
    ('Protetor Labial', 3.99),
    ('Creme para as Mãos', 5.49),
    ('Esmalte', 4.25),
    ('Removedor de Esmalte', 3.50),
    ('Base para Unhas', 6.99),
    ('Lixa de Unha', 1.25),
    ('Hidratante para Unhas', 3.99),
    ('Pincel para Maquiagem', 8.50),
    ('Sombra para Olhos', 10.75),
    ('Lápis de Olho', 5.99),
    ('Rímel', 12.50),
    ('Batom', 9.25),
    ('Gloss Labial', 7.99),
    ('Escova de Cabelo', 6.25),
    ('Pente', 2.99),
    ('Tesoura de Unha', 4.50),
    ('Escova de Limpeza Facial', 3.75),
    ('Fio Dental', 1.99),
    ('Creme de Barbear', 7.50),
    ('Pós-Barba', 5.99),
    ('Gel de Banho', 8.99),
    ('Loção Pós-Sol', 11.25),
    ('Hidratante Corporal', 9.99),
    ('Lâmina de Barbear', 12.50),
    ('Escova de Dentes', 2.99),
    ('Fio Dental', 1.99),
    ('Bálsamo Labial', 3.75),
    ('Desodorante Roll-on', 7.99),
    ('Desodorante Spray', 8.50),
    ('Esfoliante Facial', 6.25),
    ('Creme de Limpeza Facial', 5.49),
    ('Desodorante Aerosol', 9.75),
    ('Condicionador para Cabelos Danificados', 14.50),
    ('Shampoo para Cabelos Oleosos', 10.99),
    ('Condicionador para Cabelos Secos', 12.75),
    ('Shampoo para Cabelos Cacheados', 11.99),
    ('Máscara Capilar Hidratante', 13.25),
    ('Creme para Pentear', 8.99),
    ('Gel Fixador', 7.50),
    ('Spray de Fixação', 9.25),
    ('Creme para os Pés', 11.99),
    ('Spray para os Pés', 10.50),
    ('Desodorante para os Pés', 8.75),
    ('Gel Redutor de Medidas', 20.99),
    ('Creme Anticelulite', 18.50),
    ('Creme Firmador para os Seios', 25.75),
    ('Creme para Estrias', 22.99),
    ('Creme Depilatório', 13.75),
    ('Gel Pós-Barba', 9.50),
    ('Hidratante Pós-Barba', 11.25),
    ('Desodorante Íntimo', 7.99),
    ('Gel Íntimo', 9.25),
    ('Sabonete Íntimo', 5.99),
    ('Desodorante Aerosol', 8.50),
    ('Desodorante Roll-on', 7.75),
    ('Creme Depilatório Íntimo', 15.99),
    ('Hidratante Íntimo', 11.50),
    ('Creme para os Mamilos', 9.99),
    ('Creme para a Região dos Olhos', 12.75),
    ('Gel de Massagem', 16.25),
    ('Creme para Massagem', 14.99),
    ('Óleo para Massagem', 18.50),
    ('Creme Relaxante', 20.75),
    ('Espuma de Barbear', 6.99),
    ('Loção Pós-Barba', 9.50),
    ('Condicionador para Cabelos Finos', 11.75),
    ('Máscara Capilar Nutritiva', 13.99),
    ('Spray de Brilho', 8.50),
    ('Óleo Capilar', 15.25),
    ('Creme para Cutículas', 7.99),
    ('Loção Hidratante para o Corpo', 11.75),
    ('Protetor Labial com Fator de Proteção Solar', 4.99),
    ('Creme Antirrugas', 19.99),
    ('Creme Clareador para Manchas', 17.50),
    ('Creme Anti-Idade', 24.75),
    ('Creme para as Mãos com Fator de Proteção Solar', 8.99),
    ('Creme para os Pés com Ureia', 10.50),
    ('Creme para Mãos Ressecadas', 9.25),
    ('Creme para Mãos com Mel', 12.50),
    ('Creme Hidratante para Cotovelos e Joelhos', 11.99),
    ('Creme para Áreas Ressecadas', 10.75),
    ('Creme para o Rosto com Ácido Hialurônico', 18.50),
    ('Creme para Áreas com Celulite', 16.99),
    ('Creme para os Olhos com Retinol', 22.50),
    ('Creme Hidratante para a Noite', 21.25),
    ('Creme para o Dia com FPS 30', 20.99),
    ('Creme para o Dia com FPS 50', 24.50),
    ('Loção Corporal Perfumada', 13.75),
    ('Creme Hidratante com Aloe Vera', 15.99),
    ('Creme Hidratante com Óleo de Amêndoas', 14.50),
    ('Loção Corporal Relaxante', 16.25),
    ('Creme Corporal Iluminador', 19.50),
    ('Creme Corporal Firmador', 18.99),
    ('Loção Pós-Sol com Aloe Vera', 12.50),
    ('Creme para Mãos e Unhas', 10.99),
    ('Loção Pós-Barba Hidratante', 11.75),
    ('Creme Facial Hidratante com FPS 30', 22.99),
    ('Creme Facial Antirrugas', 25.50),
    ('Creme para o Contorno dos Olhos', 20.75),
    ('Creme Facial Clareador', 23.99),
    ('Creme Facial Revitalizante', 19.50),
    ('Creme Facial Noturno', 21.75),
    ('Creme Facial Diurno', 20.99),
    ('Gel de Limpeza Facial', 9.99),
    ('Creme para o Corpo com Vitamina E', 17.50),
    ('Loção Hidratante para Pele Sensível', 14.99),
    ('Creme de Barbear com Extrato de Camomila', 7.25),
    ('Creme Depilatório para Pele Sensível', 12.99),
    ('Gel de Banho Hidratante', 8.50),
    ('Loção Corporal Perfumada com Extrato de Frutas', 16.25),
    ('Creme Facial Antissinais', 23.50),
    ('Creme Corporal com Manteiga de Karité', 18.99),
    ('Creme Facial Hidratante Noturno', 22.50),
    ('Creme Corporal com Óleo de Coco', 19.75),
    ('Creme Facial Diurno com FPS 50', 27.99),
    ('Creme para Mãos com Óleo de Argan', 11.75),
    ('Loção Hidratante Corporal com Vitamina C', 15.50),
    ('Creme para os Pés com Ureia e Mentol', 13.99),
    ('Creme Corporal Anticelulite', 21.50),
    ('Creme Corporal Antiestrias', 19.99),
    ('Creme Facial Anti-Idade com Ácido Hialurônico', 28.75),
    ('Creme Facial Clareador com Vitamina C', 24.99),
    ('Creme Facial Hidratante Diurno com FPS 30', 25.75),
    ('Creme Facial Hidratante Noturno com Ácido Glicólico', 27.50),
    ('Creme Facial Revitalizante com Ouro 24K', 32.99),
    ('Creme Facial Antioxidante com Vitamina E', 29.50),
    ('Creme Facial para Peles Oleosas', 26.99),
    ('Creme Facial para Peles Secas', 28.75),
    ('Creme Facial para Peles Sensíveis', 27.25),
    ('Creme Hidratante para as Mãos com Óleo de Amêndoas', 10.99),
    ('Creme Hidratante para os Pés com Óleo de Coco', 12.75),
    ('Creme para Pentear com Óleo de Argan', 9.50),
    ('Creme Protetor para Penteados', 8.75),
    ('Gel para Cabelos Cacheados', 7.99),
    ('Gel para Cabelos Lisos', 7.50),
    ('Gel para Cabelos Ondulados', 7.75),
    ('Loção Hidratante Corporal com Vitamina E', 14.25),
    ('Loção Hidratante Facial com FPS 30', 18.99),
    ('Loção Hidratante para as Mãos com Karité', 11.50),
    ('Loção Hidratante para os Pés com Ureia', 13.25),
    ('Máscara Capilar Hidratante com Óleo de Coco', 10.99),
    ('Máscara Facial de Argila', 9.75),
    ('Óleo Corporal Hidratante com Vitamina E', 16.50),
    ('Óleo para Banho com Óleo de Amêndoas', 13.99),
    ('Protetor Solar Facial com FPS 50', 21.50),
    ('Protetor Solar Infantil com FPS 30', 19.99),
    ('Sabonete Facial de Limpeza Profunda', 8.50),
    ('Sabonete Líquido Íntimo', 6.25),
    ('Sabonete Líquido para o Corpo com Camomila', 7.99),
    ('Shampoo Anti-Resíduos', 8.99),
    ('Shampoo para Cabelos Coloridos', 9.50),
    ('Shampoo para Cabelos Danificados', 9.75),
    ('Shampoo para Cabelos Oleosos', 8.25),
    ('Shampoo para Cabelos Secos', 9.99),
    ('Spray de Brilho para Cabelos', 7.25),
    ('Spray de Fixação para Cabelos', 8.99),
    ('Tônico Capilar para Queda de Cabelo', 11.50),
    ('Creme de Barbear Hidratante', 6.75),
    ('Gel de Banho Hidratante com Aloe Vera', 9.99),
    ('Loção Pós-Barba Refrescante', 8.50),
    ('Shampoo 2 em 1 para Cabelos Normais', 9.25),
    ('Shampoo 2 em 1 para Cabelos Oleosos', 8.99),
    ('Shampoo 2 em 1 para Cabelos Secos', 9.75),
    ('Shampoo Anticaspa com Piritionato de Zinco', 10.50),
    ('Shampoo Antiqueda com Cafeína', 12.25),
    ('Shampoo para Cabelos Cacheados e Ondulados', 9.99),
    ('Shampoo para Cabelos Cacheados', 9.75),
    ('Shampoo para Cabelos Finos e Frágeis', 8.50),
    ('Shampoo para Cabelos Frágeis e Quebradiços', 9.50),
    ('Shampoo para Cabelos Loiros', 10.99),
    ('Shampoo para Cabelos Oleosos e com Caspa', 10.25),
    ('Shampoo para Cabelos Quimicamente Tratados', 11.99),
    ('Shampoo para Cabelos Ruivos', 10.75),
    ('Shampoo para Cabelos Secos e Quebradiços', 10.50),
    ('Shampoo para Cabelos Tingidos', 11.25),
    ('Shampoo para Cabelos Volumosos', 11.99),
    ('Shampoo para Prevenir a Queda de Cabelo', 12.50),
    ('Spray de Brilho para Cabelos Cacheados', 7.99),
    ('Spray de Fixação para Cabelos Cacheados', 8.75),
    ('Spray de Volume para Cabelos Finos', 9.50),
    ('Spray para Cabelos com Frizz', 8.99),
    ('Tônico Capilar Antiqueda', 11.75),
    ('Tônico Capilar para Crescimento dos Cabelos', 12.50),
    ('Creme de Barbear Refrescante', 7.25),
    ('Creme Depilatório para Pele Sensível', 13.50),
    ('Creme Hidratante para os Pés com Extrato de Mel', 11.99),
    ('Creme para Pentear com Óleo de Coco', 8.50),
    ('Desodorante Aerosol Antitranspirante', 9.75),
    ('Desodorante em Creme Antitranspirante', 8.99),
    ('Desodorante em Roll-on Antitranspirante', 9.50),
    ('Desodorante Spray Antitranspirante', 10.25),
    ('Gel de Banho com Óleo de Amêndoas', 8.75),
    ('Loção Corporal Hidratante com Óleo de Amêndoas', 13.99),
    ('Loção Corporal Perfumada com Extrato de Frutas Vermelhas', 15.50),
    ('Loção Hidratante Corporal com Aloe Vera', 11.75),
    ('Loção Hidratante Corporal com Óleo de Amêndoas', 12.99),
    ('Loção Pós-Sol com Camomila e Aloe Vera', 10.50),
    ('Máscara Capilar Hidratante com Manteiga de Karité', 9.99),
    ('Máscara Facial de Colágeno', 7.25),
    ('Óleo Corporal Hidratante com Óleo de Amêndoas', 14.50),
    ('Óleo para Banho com Óleo de Coco', 11.75),
    ('Protetor Solar Facial com FPS 50 e Vitamina E', 22.99),
    ('Protetor Solar Infantil com FPS 50 e Água Termal', 20.50),
    ('Sabonete Facial de Limpeza Profunda com Ácido Salicílico', 9.99),
    ('Sabonete Íntimo Refrescante com Extrato de Menta', 7.50),
    ('Sabonete Líquido Corporal com Óleo de Amêndoas', 8.75),
    ('Shampoo Anticaspa com Ácido Salicílico', 9.75),
    ('Shampoo para Cabelos Cacheados e Ondulados com Óleo de Coco', 10.50),
    ('Shampoo para Cabelos Cacheados com Queratina', 10.99),
    ('Shampoo para Cabelos Danificados com Arginina', 11.75),
    ('Shampoo para Cabelos Loiros com Extrato de Camomila', 10.50),
    ('Spray de Brilho para Cabelos Cacheados com Óleo de Coco', 8.99),
    ('Spray de Fixação para Cabelos Cacheados', 9.50),
    ('Tônico Capilar Antiqueda com Biotina', 13.25),
    ('Tônico Capilar para Crescimento dos Cabelos com Cafeína', 14.99),
    ('Creme de Barbear Refrescante com Extrato de Menta', 7.99),
    ('Creme Depilatório para Pele Sensível com Óleo de Amêndoas', 14.50),
    ('Creme Hidratante para os Pés com Extrato de Mel e Karité', 12.75),
    ('Creme para Pentear com Óleo de Coco e Queratina', 9.99),
    ('Desodorante Aerosol Antitranspirante com Extrato de Aloe Vera', 10.75),
    ('Desodorante em Creme Antitranspirante com Óleo de Semente de Uva', 9.99),
    ('Desodorante em Roll-on Antitranspirante com Camomila', 10.50),
    ('Desodorante Spray Antitranspirante com Vitamina E', 11.25),
    ('Gel de Banho com Óleo de Amêndoas e Vitamina E', 9.75),
    ('Loção Corporal Hidratante com Óleo de Amêndoas e Manteiga de Karité', 14.99),
    ('Loção Corporal Perfumada com Extrato de Frutas Vermelhas e Vitamina C', 16.50),
    ('Loção Hidratante Corporal com Aloe Vera e Calêndula', 12.75),
    ('Loção Hidratante Corporal com Óleo de Amêndoas e Camomila', 13.99),
    ('Loção Pós-Sol com Camomila, Aloe Vera e Vitamina E', 11.25),
    ('Máscara Capilar Hidratante com Manteiga de Karité e Óleo de Coco', 10.99),
    ('Máscara Facial de Colágeno e Ácido Hialurônico', 8.25),
    ('Óleo Corporal Hidratante com Óleo de Amêndoas e Vitamina E', 15.50),
    ('Óleo para Banho com Óleo de Coco e Vitamina E', 12.75),
    ('Protetor Solar Facial com FPS 50, Vitamina E e Ácido Hialurônico', 23.99),
    ('Protetor Solar Infantil com FPS 50, Água Termal e Camomila', 21.50),
    ('Sabonete Facial de Limpeza Profunda com Ácido Salicílico e Hamamélis', 10.25),
    ('Sabonete Íntimo Refrescante com Extrato de Menta e Calêndula', 8.99),
    ('Sabonete Líquido Corporal com Óleo de Amêndoas e Calêndula', 9.75),
    ('Shampoo Anticaspa com Ácido Salicílico e Extrato de Hortelã', 10.50),
    ('Shampoo para Cabelos Cacheados e Ondulados com Óleo de Coco e Queratina', 11.25),
    ('Shampoo para Cabelos Cacheados com Queratina e Manteiga de Karité', 11.99),
    ('Shampoo para Cabelos Danificados com Arginina e Proteína do Trigo', 12.75),
    ('Shampoo para Cabelos Loiros com Extrato de Camomila e Proteína do Leite', 11.50),
    ('Spray de Brilho para Cabelos Cacheados com Óleo de Coco e Queratina', 9.25),
    ('Spray de Fixação para Cabelos Cacheados com Extrato de Colágeno', 10.50),
    ('Tônico Capilar Antiqueda com Biotina e Cafeína', 14.25),
    ('Tônico Capilar para Crescimento dos Cabelos com Cafeína e Arginina', 15.99),
    ('Creme de Barbear Refrescante com Extrato de Menta e Camomila', 8.75),
    ('Creme Depilatório para Pele Sensível com Óleo de Amêndoas e Calêndula', 15.50),
    ('Creme Hidratante para os Pés com Extrato de Mel, Karité e Ureia', 13.25),
    ('Creme para Pentear com Óleo de Coco, Queratina e Vitamina E', 10.50),
    ('Desodorante Aerosol Antitranspirante com Extrato de Aloe Vera e Camomila', 11.75),
    ('Desodorante em Creme Antitranspirante com Óleo de Semente de Uva e Vitamina C', 10.99),
    ('Desodorante em Roll-on Antitranspirante com Camomila e Alantoína', 11.50),
    ('Desodorante Spray Antitranspirante com Vitamina E e Aloe Vera', 12.25),
    ('Gel de Banho com Óleo de Amêndoas e Vitamina E', 10.75),
    ('Loção Corporal Hidratante com Óleo de Amêndoas, Manteiga de Karité e Colágeno', 15.50),
    ('Loção Corporal Perfumada com Extrato de Frutas Vermelhas, Vitamina C e Ácido Hialurônico', 17.25),
    ('Loção Hidratante Corporal com Aloe Vera, Calêndula e Óleo de Coco', 13.50),
    ('Loção Hidratante Corporal com Óleo de Amêndoas, Camomila e Vitamina E', 14.75),
    ('Loção Pós-Sol com Camomila, Aloe Vera, Vitamina E e Pantenol', 12.00),
    ('Máscara Capilar Hidratante com Manteiga de Karité, Óleo de Coco e Vitamina E', 11.75),
    ('Máscara Facial de Colágeno, Ácido Hialurônico e Vitamina C', 9.50),
    ('Óleo Corporal Hidratante com Óleo de Amêndoas, Vitamina E e Extrato de Aloe Vera', 16.75),
    ('Óleo para Banho com Óleo de Coco, Vitamina E e Extrato de Camomila', 13.50),
    ('Protetor Solar Facial com FPS 50, Vitamina E, Ácido Hialurônico e Antioxidantes', 24.25),
    ('Protetor Solar Infantil com FPS 50, Água Termal, Camomila e Extrato de Calêndula', 22.00),
    ('Sabonete Facial de Limpeza Profunda com Ácido Salicílico, Hamamélis e Extrato de Pepino', 11.75),
    ('Sabonete Íntimo Refrescante com Extrato de Menta, Calêndula e Ácido Lático', 9.50),
    ('Sabonete Líquido Corporal com Óleo de Amêndoas, Calêndula e Extrato de Lavanda', 10.75),
    ('Shampoo Anticaspa com Ácido Salicílico, Extrato de Hortelã e Pantenol', 11.50),
    ('Shampoo para Cabelos Cacheados e Ondulados com Óleo de Coco, Queratina e D-Pantenol', 12.25),
    ('Shampoo para Cabelos Cacheados com Queratina, Manteiga de Karité e Óleo de Argan', 12.99),
    ('Shampoo para Cabelos Danificados com Arginina, Proteína do Trigo e Vitamina E', 13.75),
    ('Shampoo para Cabelos Loiros com Extrato de Camomila, Proteína do Leite e Óleo de Argan', 12.50),
    ('Spray de Brilho para Cabelos Cacheados com Óleo de Coco, Queratina e D-Pantenol', 10.25),
    ('Spray de Fixação para Cabelos Cacheados com Extrato de Colágeno, Elastina e Óleo de Abacate', 11.50),
    ('Tônico Capilar Antiqueda com Biotina, Cafeína e D-Pantenol', 15.25),
    ('Tônico Capilar para Crescimento dos Cabelos com Cafeína, Arginina e Extrato de Jaborandi', 16.99);
