version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: . 
    ports:
      - "3001:3001"  # Certificando que a porta exposta pelo container é mapeada para a mesma porta no host
    environment:
      DB_URI: mongodb://root:example@mongo:27017/myauthdb?authSource=admin
      JWT_SECRET: supersecretkey
    depends_on:
      - mongo

volumes:
  mongo-data:
